### ISSUE TITLE
Will not build with g++ 9.3

### ISSUE THREAD

**Issue by tukkek** [caligari87/Oblige#9]
```
gui/csg_clip.cc: In function ‘void DoWriteClip(dclipnode_t&, bool)’:
gui/csg_clip.cc:1057:32: error: cannot bind packed field ‘raw_clip.dclipnode_s::children[0]’ to ‘short unsigned int&’
 1057 |   std::swap(raw_clip.children[0], raw_clip.children[1]);
      |             ~~~~~~~~~~~~~~~~~~~^
make: *** [Makefile:106: obj_linux/csg_clip.o] Error 1

```

Thanks to [this comment](https://aur.archlinux.org/packages/oblige-git/#comment-737988) though, I have been able to properly compile Oblige after installing `g++ 8 8.4`. This can easily be done by changing [this line](https://github.com/caligari87/Oblige/blob/b4fbd901404eeefb4b522a1fb065b626160c6fe3/Makefile#L20) to:

    CXX=g++-8

My suggestions towards solving this problem:

1. Fix the compilation error(s) to work with the latest version of `g++`; or...
2. Update the documentation files and Makefile to officially and explicitly depend on `g++ 8`.

Given that the second approach is a simple-enough task and within my technical knowledge. I'd be happy to draft a pull request for that. However, I'd imagine the first option is probably the more future-proof way of addressing the issue.
